var dir_641b8b8e3260d4a59b2619379fe317e3 =
[
    [ "Change Event Listeners", "dir_fa06c226b242df5540232c7f4cc5bf04.html", "dir_fa06c226b242df5540232c7f4cc5bf04" ],
    [ "Change Events", "dir_b08fe587e21f031778b347cc14f6817d.html", "dir_b08fe587e21f031778b347cc14f6817d" ],
    [ "Game Event Listeners", "dir_418f2c1caa9b89f3386ee33affb5ff7b.html", "dir_418f2c1caa9b89f3386ee33affb5ff7b" ],
    [ "Game Events", "dir_f97f07d75024de4da357e66b15484f1d.html", "dir_f97f07d75024de4da357e66b15484f1d" ],
    [ "CollisionEnterSender.cs", "_collision_enter_sender_8cs.html", [
      [ "CollisionEnterSender", "class_heathen_engineering_1_1_events_1_1_collision_enter_sender.html", "class_heathen_engineering_1_1_events_1_1_collision_enter_sender" ]
    ] ],
    [ "CollisionExitSender.cs", "_collision_exit_sender_8cs.html", [
      [ "CollisionExitSender", "class_heathen_engineering_1_1_events_1_1_collision_exit_sender.html", "class_heathen_engineering_1_1_events_1_1_collision_exit_sender" ]
    ] ],
    [ "CollisionStaySender.cs", "_collision_stay_sender_8cs.html", [
      [ "CollisionStaySender", "class_heathen_engineering_1_1_events_1_1_collision_stay_sender.html", "class_heathen_engineering_1_1_events_1_1_collision_stay_sender" ]
    ] ],
    [ "TriggerEnterSender.cs", "_trigger_enter_sender_8cs.html", [
      [ "TriggerEnterSender", "class_heathen_engineering_1_1_events_1_1_trigger_enter_sender.html", "class_heathen_engineering_1_1_events_1_1_trigger_enter_sender" ]
    ] ],
    [ "TriggerExitSender.cs", "_trigger_exit_sender_8cs.html", [
      [ "TriggerExitSender", "class_heathen_engineering_1_1_events_1_1_trigger_exit_sender.html", "class_heathen_engineering_1_1_events_1_1_trigger_exit_sender" ]
    ] ],
    [ "TriggerStaySender.cs", "_trigger_stay_sender_8cs.html", [
      [ "TriggerStaySender", "class_heathen_engineering_1_1_events_1_1_trigger_stay_sender.html", "class_heathen_engineering_1_1_events_1_1_trigger_stay_sender" ]
    ] ],
    [ "UnityCustomEvents.cs", "_unity_custom_events_8cs.html", [
      [ "UnitySceneProcessStateEvent", "class_heathen_engineering_1_1_events_1_1_unity_scene_process_state_event.html", null ],
      [ "UnityDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_data_event.html", null ],
      [ "UnityDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_data_event.html", null ],
      [ "UnityChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_change_event.html", null ],
      [ "UnityCollectionChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_collection_change_event.html", null ],
      [ "UnitySystemObjectEvent", "class_heathen_engineering_1_1_events_1_1_unity_system_object_event.html", null ],
      [ "UnityObjectEvent", "class_heathen_engineering_1_1_events_1_1_unity_object_event.html", null ],
      [ "UnityFloatEvent", "class_heathen_engineering_1_1_events_1_1_unity_float_event.html", null ],
      [ "UnityIntEvent", "class_heathen_engineering_1_1_events_1_1_unity_int_event.html", null ],
      [ "UnityBoolEvent", "class_heathen_engineering_1_1_events_1_1_unity_bool_event.html", null ],
      [ "UnityDoubleEvent", "class_heathen_engineering_1_1_events_1_1_unity_double_event.html", null ],
      [ "UnityLongEvent", "class_heathen_engineering_1_1_events_1_1_unity_long_event.html", null ],
      [ "UnityUnsignedLongEvent", "class_heathen_engineering_1_1_events_1_1_unity_unsigned_long_event.html", null ],
      [ "UnityUnsignedIntEvent", "class_heathen_engineering_1_1_events_1_1_unity_unsigned_int_event.html", null ],
      [ "UnityStringEvent", "class_heathen_engineering_1_1_events_1_1_unity_string_event.html", null ],
      [ "UnityColorEvent", "class_heathen_engineering_1_1_events_1_1_unity_color_event.html", null ],
      [ "UnitySerializableColorEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_color_event.html", null ],
      [ "UnitySpriteEvent", "class_heathen_engineering_1_1_events_1_1_unity_sprite_event.html", null ],
      [ "UnityTextureEvent", "class_heathen_engineering_1_1_events_1_1_unity_texture_event.html", null ],
      [ "UnityRigidbodyEvent", "class_heathen_engineering_1_1_events_1_1_unity_rigidbody_event.html", null ],
      [ "UnityColliderEvent", "class_heathen_engineering_1_1_events_1_1_unity_collider_event.html", null ],
      [ "UnityCollisionEvent", "class_heathen_engineering_1_1_events_1_1_unity_collision_event.html", null ],
      [ "UnityTransformEvent", "class_heathen_engineering_1_1_events_1_1_unity_transform_event.html", null ],
      [ "UnitySerializableTransformEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_transform_event.html", null ],
      [ "UnitySerializableRectTransformEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_rect_transform_event.html", null ],
      [ "UnityRectTransformEvent", "class_heathen_engineering_1_1_events_1_1_unity_rect_transform_event.html", null ],
      [ "UnityGameObjectEvent", "class_heathen_engineering_1_1_events_1_1_unity_game_object_event.html", null ],
      [ "UnityVector2Event", "class_heathen_engineering_1_1_events_1_1_unity_vector2_event.html", null ],
      [ "UnityVector2IntEvent", "class_heathen_engineering_1_1_events_1_1_unity_vector2_int_event.html", null ],
      [ "UnitySerializableVector2Event", "class_heathen_engineering_1_1_events_1_1_unity_serializable_vector2_event.html", null ],
      [ "UnitySerializableVector2IntEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_vector2_int_event.html", null ],
      [ "UnityVector3Event", "class_heathen_engineering_1_1_events_1_1_unity_vector3_event.html", null ],
      [ "UnitySerializableVector3Event", "class_heathen_engineering_1_1_events_1_1_unity_serializable_vector3_event.html", null ],
      [ "UnityVector4Event", "class_heathen_engineering_1_1_events_1_1_unity_vector4_event.html", null ],
      [ "UnitySerializableVector4Event", "class_heathen_engineering_1_1_events_1_1_unity_serializable_vector4_event.html", null ],
      [ "UnityQuaternionEvent", "class_heathen_engineering_1_1_events_1_1_unity_quaternion_event.html", null ],
      [ "UnitySerializableQuaternionEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_quaternion_event.html", null ],
      [ "UnitySystemObjectDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_system_object_data_event.html", null ],
      [ "UnityObjectDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_object_data_event.html", null ],
      [ "UnityFloatDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_float_data_event.html", null ],
      [ "UnityIntDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_int_data_event.html", null ],
      [ "UnityBoolDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_bool_data_event.html", null ],
      [ "UnityDoubleDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_double_data_event.html", null ],
      [ "UnityLongDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_long_data_event.html", null ],
      [ "UnityUnsignedLongDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_unsigned_long_data_event.html", null ],
      [ "UnityUnsignedIntDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_unsigned_int_data_event.html", null ],
      [ "UnityStringDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_string_data_event.html", null ],
      [ "UnityColorDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_color_data_event.html", null ],
      [ "UnitySerializableColorDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_color_data_event.html", null ],
      [ "UnitySpriteDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_sprite_data_event.html", null ],
      [ "UnityTextureDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_texture_data_event.html", null ],
      [ "UnityRigidbodyDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_rigidbody_data_event.html", null ],
      [ "UnityColliderDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_collider_data_event.html", null ],
      [ "UnityCollisionDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_collision_data_event.html", null ],
      [ "UnityTransformDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_transform_data_event.html", null ],
      [ "UnityRectTransformDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_rect_transform_data_event.html", null ],
      [ "UnityGameObjectDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_game_object_data_event.html", null ],
      [ "UnityVector2DataEvent", "class_heathen_engineering_1_1_events_1_1_unity_vector2_data_event.html", null ],
      [ "UnityVector2IntDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_vector2_int_data_event.html", null ],
      [ "UnitySerializableVector2DataEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_vector2_data_event.html", null ],
      [ "UnitySerializableVector2IntDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_vector2_int_data_event.html", null ],
      [ "UnityVector3DataEvent", "class_heathen_engineering_1_1_events_1_1_unity_vector3_data_event.html", null ],
      [ "UnitySerializableVector3DataEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_vector3_data_event.html", null ],
      [ "UnityVector4DataEvent", "class_heathen_engineering_1_1_events_1_1_unity_vector4_data_event.html", null ],
      [ "UnitySerializableVector4DataEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_vector4_data_event.html", null ],
      [ "UnitySerializableTransfromDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_transfrom_data_event.html", null ],
      [ "UnitySerializableRectTransfromDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_rect_transfrom_data_event.html", null ],
      [ "UnitySerializableQuaternionDataEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_quaternion_data_event.html", null ],
      [ "UnitySystemObjectChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_system_object_change_event.html", null ],
      [ "UnityObjectChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_object_change_event.html", null ],
      [ "UnityFloatChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_float_change_event.html", null ],
      [ "UnityIntChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_int_change_event.html", null ],
      [ "UnityBoolChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_bool_change_event.html", null ],
      [ "UnityDoubleChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_double_change_event.html", null ],
      [ "UnityLongChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_long_change_event.html", null ],
      [ "UnityUnsignedLongChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_unsigned_long_change_event.html", null ],
      [ "UnityUnsignedIntChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_unsigned_int_change_event.html", null ],
      [ "UnityStringChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_string_change_event.html", null ],
      [ "UnityColorChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_color_change_event.html", null ],
      [ "UnitySerializableColorChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_color_change_event.html", null ],
      [ "UnitySpriteChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_sprite_change_event.html", null ],
      [ "UnityTextureChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_texture_change_event.html", null ],
      [ "UnityRigidbodyChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_rigidbody_change_event.html", null ],
      [ "UnityColliderChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_collider_change_event.html", null ],
      [ "UnityCollisionChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_collision_change_event.html", null ],
      [ "UnityTransformChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_transform_change_event.html", null ],
      [ "UnityRectTransformChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_rect_transform_change_event.html", null ],
      [ "UnityGameObjectChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_game_object_change_event.html", null ],
      [ "UnityVector2ChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_vector2_change_event.html", null ],
      [ "UnityVector2IntChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_vector2_int_change_event.html", null ],
      [ "UnitySerializableVector2ChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_vector2_change_event.html", null ],
      [ "UnitySerializableVector2IntChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_vector2_int_change_event.html", null ],
      [ "UnityVector3ChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_vector3_change_event.html", null ],
      [ "UnitySerializableVector3ChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_vector3_change_event.html", null ],
      [ "UnityVector4ChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_vector4_change_event.html", null ],
      [ "UnitySerializableVector4ChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_vector4_change_event.html", null ],
      [ "UnitySerializableTransformChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_transform_change_event.html", null ],
      [ "UnitySerializableRectTransformChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_rect_transform_change_event.html", null ],
      [ "UnitySerializableQuaternionChangeEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_quaternion_change_event.html", null ],
      [ "UnitySystemObjectCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_system_object_collection_event.html", null ],
      [ "UnityObjectCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_object_collection_event.html", null ],
      [ "UnityFloatCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_float_collection_event.html", null ],
      [ "UnityIntCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_int_collection_event.html", null ],
      [ "UnityBoolCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_bool_collection_event.html", null ],
      [ "UnityDoubleCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_double_collection_event.html", null ],
      [ "UnityLongCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_long_collection_event.html", null ],
      [ "UnityUnsignedLongCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_unsigned_long_collection_event.html", null ],
      [ "UnityUnsignedIntCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_unsigned_int_collection_event.html", null ],
      [ "UnityStringCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_string_collection_event.html", null ],
      [ "UnityColorCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_color_collection_event.html", null ],
      [ "UnitySerializableColorCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_color_collection_event.html", null ],
      [ "UnitySpriteCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_sprite_collection_event.html", null ],
      [ "UnityTextureCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_texture_collection_event.html", null ],
      [ "UnityRigidbodyCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_rigidbody_collection_event.html", null ],
      [ "UnityColliderCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_collider_collection_event.html", null ],
      [ "UnityCollisionCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_collision_collection_event.html", null ],
      [ "UnityTransformCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_transform_collection_event.html", null ],
      [ "UnityRectTransformCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_rect_transform_collection_event.html", null ],
      [ "UnityGameObjectCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_game_object_collection_event.html", null ],
      [ "UnityVector2CollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_vector2_collection_event.html", null ],
      [ "UnityVector2IntCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_vector2_int_collection_event.html", null ],
      [ "UnitySerializableVector2CollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_vector2_collection_event.html", null ],
      [ "UnitySerializableVector2IntCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_vector2_int_collection_event.html", null ],
      [ "UnityVector3CollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_vector3_collection_event.html", null ],
      [ "UnitySerializableVector3CollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_vector3_collection_event.html", null ],
      [ "UnityVector4CollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_vector4_collection_event.html", null ],
      [ "UnitySerializableVector4CollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_serializable_vector4_collection_event.html", null ],
      [ "UnityQuaternionCollectionEvent", "class_heathen_engineering_1_1_events_1_1_unity_quaternion_collection_event.html", null ],
      [ "UnitySenderFloatEvent", "class_heathen_engineering_1_1_events_1_1_unity_sender_float_event.html", null ],
      [ "UnitySenderIntEvent", "class_heathen_engineering_1_1_events_1_1_unity_sender_int_event.html", null ],
      [ "UnitySenderBoolEvent", "class_heathen_engineering_1_1_events_1_1_unity_sender_bool_event.html", null ],
      [ "UnitySenderDoubleEvent", "class_heathen_engineering_1_1_events_1_1_unity_sender_double_event.html", null ],
      [ "UnitySenderStringEvent", "class_heathen_engineering_1_1_events_1_1_unity_sender_string_event.html", null ],
      [ "UnitySenderColorEvent", "class_heathen_engineering_1_1_events_1_1_unity_sender_color_event.html", null ],
      [ "UnitySenderSpriteEvent", "class_heathen_engineering_1_1_events_1_1_unity_sender_sprite_event.html", null ],
      [ "UnitySenderTextureEvent", "class_heathen_engineering_1_1_events_1_1_unity_sender_texture_event.html", null ],
      [ "UnitySenderRigidbodyEvent", "class_heathen_engineering_1_1_events_1_1_unity_sender_rigidbody_event.html", null ],
      [ "UnitySenderColliderEvent", "class_heathen_engineering_1_1_events_1_1_unity_sender_collider_event.html", null ],
      [ "UnitySenderCollisionEvent", "class_heathen_engineering_1_1_events_1_1_unity_sender_collision_event.html", null ],
      [ "UnitySenderTransformEvent", "class_heathen_engineering_1_1_events_1_1_unity_sender_transform_event.html", null ],
      [ "UnitySenderRectTransformEvent", "class_heathen_engineering_1_1_events_1_1_unity_sender_rect_transform_event.html", null ],
      [ "UnitySenderGameObjectEvent", "class_heathen_engineering_1_1_events_1_1_unity_sender_game_object_event.html", null ],
      [ "UnitySenderVector2Event", "class_heathen_engineering_1_1_events_1_1_unity_sender_vector2_event.html", null ],
      [ "UnitySenderVector3Event", "class_heathen_engineering_1_1_events_1_1_unity_sender_vector3_event.html", null ],
      [ "UnitySenderVector4Event", "class_heathen_engineering_1_1_events_1_1_unity_sender_vector4_event.html", null ],
      [ "UnitySenderQuaternionEvent", "class_heathen_engineering_1_1_events_1_1_unity_sender_quaternion_event.html", null ],
      [ "VariableEvent", "class_heathen_engineering_1_1_events_1_1_variable_event.html", null ],
      [ "VariableFloatEvent", "class_heathen_engineering_1_1_events_1_1_variable_float_event.html", null ],
      [ "VariableIntEvent", "class_heathen_engineering_1_1_events_1_1_variable_int_event.html", null ],
      [ "VariableBoolEvent", "class_heathen_engineering_1_1_events_1_1_variable_bool_event.html", null ],
      [ "VariableStringEvent", "class_heathen_engineering_1_1_events_1_1_variable_string_event.html", null ],
      [ "VariableDoubleEvent", "class_heathen_engineering_1_1_events_1_1_variable_double_event.html", null ],
      [ "VariableColorEvent", "class_heathen_engineering_1_1_events_1_1_variable_color_event.html", null ],
      [ "VariableVector2Event", "class_heathen_engineering_1_1_events_1_1_variable_vector2_event.html", null ],
      [ "VariableVector3Event", "class_heathen_engineering_1_1_events_1_1_variable_vector3_event.html", null ],
      [ "VariableVector4Event", "class_heathen_engineering_1_1_events_1_1_variable_vector4_event.html", null ]
    ] ]
];